Workaround for error in simple_oauth
```
  1) SimpleTwitter::Client post with form (API v1.1) [:media_id]
     Failure/Error: SimpleOAuth::Header.new(method, url, params, @oauth_params).to_s

     NoMethodError:
       undefined method 'parse' for class CGI
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:122:in 'SimpleOAuth::Header#url_params'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:118:in 'SimpleOAuth::Header#signature_params'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:114:in 'SimpleOAuth::Header#normalized_params'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:110:in 'SimpleOAuth::Header#signature_base'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:101:in 'SimpleOAuth::Header#hmac_sha1_signature'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:97:in 'SimpleOAuth::Header#signature'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:77:in 'SimpleOAuth::Header#signed_attributes'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:83:in 'SimpleOAuth::Header#normalized_attributes'
     # ./vendor/bundle/ruby/4.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:65:in 'SimpleOAuth::Header#to_s'
     # ./lib/simple_twitter/client.rb:161:in 'SimpleTwitter::Client#auth_header'
     # ./lib/simple_twitter/client.rb:150:in 'SimpleTwitter::Client#http'
     # ./lib/simple_twitter/client.rb:122:in 'SimpleTwitter::Client#post_raw'
     # ./lib/simple_twitter/client.rb:116:in 'SimpleTwitter::Client#post'
     # ./spec/simple_twitter/client_spec.rb:55:in 'block (3 levels) in <top (required)>'
     # ./spec/simple_twitter/client_spec.rb:82:in 'block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/4.0.0/gems/webmock-3.26.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'
```